spring.application.name=progetto_finale
spring.datasource.url=jdbc:mysql://localhost:3306/progettoFinaleStudente
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

supabase.url=https://zdmkfcbigzixieajnxva.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbWtmY2JpZ3ppeGllYWpueHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4OTgwODksImV4cCI6MjEwMzQ3NDA4OX0.i61Mxo3BSaT2qmen1Nx7e9pZg1n4HTuUaEZkKdDWcHM
supabase.bucket=/storage/v1/object/Progetto-finale/
supabase.image=/storage/v1/object/public/Progetto-finale/

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=c2dc5353a9c92e
spring.mail.password=af1ae86abeaa2e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true